debug: false
deepspeed_config:
  deepspeed_config_file:  zero3_offload.json
  deepspeed_multinode_launcher: standard
  zero3_init_flag: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
num_machines: 1
num_processes: 8
main_process_port: 38222
main_training_function: main
rdzv_backend: c10d
same_network: false
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
